language: node_js
node_js:
  - 10.9.0
cache:
  directories:
    - ~/.npm
env:
  global:
    - TRUNK_BRANCH="master"
before_script:
  - npm i -g npm@6.2.0
install:
  - npm ci
  - source ./ci/create-dotenv.sh
script: skip
jobs:
  include:
    - stage: test
      script:
        - npm run prestart
        - npm run test:ci
    # - stage: release
    #   if: branch = env(TRUNK_BRANCH) AND type = push
    #   script:
    #     - source ./ci/prepare-release.sh || travis_terminate 1
    #     - npm run release || travis_terminate 1
    #     - git remote set-url origin https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git
    #     - git push --follow-tags origin $TRAVIS_BRANCH || travis_terminate 1
    - stage: deploy
      if: branch = env(TRUNK_BRANCH) AND type = push
      script:
        - source ./ci/deploy.sh || travis_terminate 1
